const EMPTY_STRING = ''

const ZERO = 0
const ONE = 1
const TWO = 2
const THREE = 3
const FOUR = 4
const FIVE = 5
const SIX = 6
const SEVEN = 7
const EIGHT = 8
const NINE = 9
const TEN = 10
const SIXTEEN = 16
const HUNDRED = 100

const INDEX_NOT_FOUND = -1
const DEFAULT_GET_LIMIT = 28

const MILLISECONDS_IN_SECOND = 1000

const ONE_SECOND = ONE
const SECONDS_PER_MINUTE = 60
const MINUTES_PER_HOUR = 60
const HOURS_PER_DAY = 24

const SECONDS_IN_MINUTE = ONE_SECOND * SECONDS_PER_MINUTE
const SECONDS_IN_HOUR = SECONDS_IN_MINUTE * MINUTES_PER_HOUR
const SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_PER_DAY

const MILLISECONDS_IN_MINUTE =
    ONE_SECOND * SECONDS_PER_MINUTE * MILLISECONDS_IN_SECOND
const MILLISECONDS_IN_HOUR = MILLISECONDS_IN_MINUTE * MINUTES_PER_HOUR
const MILLISECONDS_IN_DAY = MILLISECONDS_IN_HOUR * HOURS_PER_DAY

const INIT_DAY = new Date()

const CURRENT_DAY = new Date(
    INIT_DAY.getFullYear(),
    INIT_DAY.getMonth(),
    INIT_DAY.getDate(),
)
const CURRENT_END_DAY = new Date(
    INIT_DAY.getFullYear(),
    INIT_DAY.getMonth(),
    INIT_DAY.getDate(),
    ZERO,
    ZERO,
    -ONE,
)

const ONE_DAY = 1
const DAYS_IN_WEEK = 7
const DAYS_IN_MONTH = 30
const DAYS_IN_YEAR = 365

export {
    EMPTY_STRING,
    ZERO,
    ONE,
    TWO,
    THREE,
    FOUR,
    FIVE,
    SIX,
    SEVEN,
    EIGHT,
    NINE,
    TEN,
    SIXTEEN,
    HUNDRED,
    INDEX_NOT_FOUND,
    DEFAULT_GET_LIMIT,
    MILLISECONDS_IN_SECOND,
    ONE_SECOND,
    SECONDS_PER_MINUTE,
    MINUTES_PER_HOUR,
    HOURS_PER_DAY,
    SECONDS_IN_MINUTE,
    SECONDS_IN_HOUR,
    SECONDS_IN_DAY,
    MILLISECONDS_IN_MINUTE,
    MILLISECONDS_IN_HOUR,
    MILLISECONDS_IN_DAY,
    INIT_DAY,
    CURRENT_DAY,
    CURRENT_END_DAY,
    ONE_DAY,
    DAYS_IN_WEEK,
    DAYS_IN_MONTH,
    DAYS_IN_YEAR,
}
